FROM {{ osm2pgsql.base_image }}:{{ osm2pgsql.base_image_version }}
RUN apt update
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:ubuntugis/ppa
RUN apt update
RUN apt install apt-transport-https -y
RUN apt install -y python3-pip
RUN pip3 install psycopg2-binary
RUN pip3 install pika
RUN apt-get install osm2pgsql -y

ENV PYTHONUNBUFFERED=1

WORKDIR /opt/osm2pgsql
COPY main.py main.py



CMD ["python3", "-u", "main.py"]